### ISSUE TITLE
TC Charter Comments: Section 5 Responsibilities of the TC

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/ISIS_TC#64]
This issue is for comments and proposed changes to section 5 of the [TC Charter](https://github.com/USGS-Astrogeology/ISIS_TC/blob/master/TC-Charter.md#section-5-responsibilities-of-the-tc).

**Comment by rbeyer** [comment]
If you have read my other comments about the Charter and are frustrated about my desire to remove mention of 'ASC Management' from the document, I'm hoping that the suggested rewrites here will help you understand where I'm coming from.  I think the goal of the TC should be to establish guidelines and best practices.  It cannot be responsible for carrying out actions (like writing and committing code), that must be left to the community members (including the ASC-funded developers which are directed by their management to work on the ISIS codebase).

So my suggested rewrites come from that perspective.  See what you think.

I would rewrite the opening paragraph to read:

> The TC is responsible for setting policies for the technical development of the ISIS Software Project, including:

This makes it clear the the TC isn't "responsible for all technical development" (that's crazy, this is a volunteer organization, how can it be responsible for that), but makes it clear that the TSC dreams up the policies and guidelines, and then the expectation is that members of the community that want to make commits would follow those guidelines.

Original | Change
--------|---------
Setting release dates. | Release dates.
Release quality standards. | *no change*
Technical direction. | *no change*
Project governance and process (including this policy). | *no change*
GitHub repository hosting. | Location of the official software repository.
Conduct guidelines. | *no change*
Maintaining the list of Collaborators. | *no change*
Development process and coding standards. | Contribution guidelines (including coding and testing standards).
Mediating technical conflicts between Collaborators. | *no change*
*moved up from final sentence* | Release process and mechanisms

Then I'd rewrite the final sentence to read:

> The TC will serve as the ISIS Software Project's primary technical liaison body with external open source projects, consortiums, and groups.

**Comment by jessemapel** [comment]
I feel like "release quality standards" and "release dates" are a part of "release process and mechanisms".

I like the idea of the TC being the technical liaison for external entities. I don't think the ASC needs to be especially enshrined in the charter, but there does need to be an agreement between the ASC management team and the ISIS TC about some key technical points:

1. Will ISIS continue to be hosted on the ASC's github organization? What permissions does the TC need to have in the ASC organization to make this work?
1. The ASC needs the ability to unilaterally make some technical decisions while the ISIS TC is organizing. We (the ASC) has obligations to deliver specific functionality and fixes via ISIS and we cannot halt work while the TC is organizing. I'd like to see a gradual transfer of responsibilities from the ASC to the TC.

**Comment by rbeyer** [comment]
> I feel like "release quality standards" and "release dates" are a part of "release process and mechanisms".

Fair enough, I was thinking too atomically.  Probably having just "Release Processes and Mechanisms (including release dates and quality standards)." would be fine.


> I like the idea of the TC being the technical liaison for external entities. I don't think the ASC needs to be especially enshrined in the charter, but there does need to be an agreement between the ASC management team and the ISIS TC about some key technical points:
> 
> 1. Will ISIS continue to be hosted on the ASC's github organization? What permissions does the TC need to have in the ASC organization to make this work?

Great question, but I would instead ask: "will ASC continue to volunteer to host the ISIS repo?"  I would hope the answer would be yes, and I would expect that to be non-controversial amongst the TC.  Then your following question about the 'ASC *GitHub* organization' is relevant (I'm assuming you didn't mean the possibly more generic interpretation).  Clearly, there is no impediment from doing so via GitHub, but are you talking about any restrictions on *how* things are done based on DOI policies or something, such that would require the repo to not be hosted under your GitHub org?

> 2. The ASC needs the ability to unilaterally make some technical decisions while the ISIS TC is organizing. We (the ASC) have obligations to deliver specific functionality and fixes via ISIS and we cannot halt work while the TC is organizing. I'd like to see a gradual transfer of responsibilities from the ASC to the TC.

I'd like to talk more about this (probably at our next voice meeting), because there are very likely aspects that I'm not appreciating.  I do completely understand that a transition from 'no TC' to 'TC' in the ISIS software project is going to have a lot of impact, and is very different from what we all might envision for a 'steady state.'

I don't necessarily have a problem with a 'gradual transfer,' in fact that is probably very wise.  As always, how we implement it is important.  I think we should enumerate all of the 'TC' responsibilities that we think are appropriate for the 'steady state' condition but 'comment them out' in the charter (so they are written down there, but not in effect), and then as both groups are ready for the TC to take on a responsibility, then we can amend the charter, slowly pulling all of the items that are 'commented out' into effect.  In fact, you could think of the current state as being all responsibilities being 'commented out' and the TC having none.

**Comment by rfergason** [comment]
In our last meeting, I recall "Technical direction." being stripped from the list of TC responsibilities. I would argue that technical direction does not fall under "policy and procedures", which was the broad TC purview described above.  This discussion suggests that we need to revisit this topic.

**Comment by jlaura** [comment]
I agree with the release/release dates, etc. comments and like the other update to the table. 

On the technical direction comment: I would suggest that the folks with commit rights on repo have ultimate control over the technical direction. It would be immensely beneficial if the TC could lay out some broad guidelines about what is in and out of scope for the ISIS project. To me, the TC is an in/out of scope organization and the committing members of the project are a technical direction / how group.

**Comment by rbeyer** [comment]
I think #91 and #92 clear this thread.
